spring:
  application: 
          name:first
  datasource:
          url: jdbc:postgresql://localhost:5432/test
          username: postgres
          password: 123456789
          driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        format_sql : true       

